export const NUMBER_OF_STARS = 100;
// export const Y_AXIS_ROTATION_SPEED = 0.0005;
export const Y_AXIS_ROTATION_SPEED = 0;

export const PLANETARY_SYSTEM_DISTANCE_SCALING_FACTOR = 0.00023;

export const PLANETARY_RA_SCALING_FACTOR = 0.001;
export const PLANETARY_DEC_SCALING_FACTOR = 0.001;
